import type { NextPage } from 'next'
import Head from 'next/head'

import { trpc } from 'utils/trpc'

type TechnologyCardProps = {
  name: string
  description: string
  documentation: string
}

const Home: NextPage = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>
        <select>
          <option>name_of_repo</option>
        </select>
        <input type="password" name="token" />
        <button>submit</button>
      </main>
    </>
  )
}

export default Home
